//修改游记
export const SET_UPDATATRAVELS="SET_UPDATATRAVELS";
//登录成功
export const SET_LOGINSUCCESS="SET_LOGINSUCCESS";
//游记
export const SET_TRAVELSDATEIL="SET_TRAVELSDATEIL";
//游记显示
export const SET_TRAVELSDATEILSHOW="SET_TRAVELSDATEILSHOW";
