//修改游记
export const SET_UPDATATRAVELS="SET_UPDATATRAVELS";
//登录成功
export const SET_LOGINSUCCESS="SET_LOGINSUCCESS";
//游记
export const SET_TRAVELSDATEIL="SET_TRAVELSDATEIL";
//游记显示
export const SET_TRAVELSDATEILSHOW="SET_TRAVELSDATEILSHOW";
//写游记
export const SET_WRITETRAVELS="SET_WRITETRAVELS";
//关注详情
export const SET_ATTENTIONDATA="SET_ATTENTIONDATA";
//景点
export const SET_VIEWSPOTDETAIL="SET_VIEWSPOTDETAIL";
//客服
export const SET_CHAT="SET_CHAT";
